"""empty message

Revision ID: 2fdb5ec7efa3
Revises: 5ef7fb6b3cde
Create Date: 2024-11-08 12:37:17.196116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fdb5ec7efa3'
down_revision = '5ef7fb6b3cde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('task_goal_id_fkey', type_='foreignkey')
        batch_op.drop_column('goal_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('task_goal_id_fkey', 'goal', ['goal_id'], ['id'])

    # ### end Alembic commands ###
